// Do not edit. This file is machine generated by the Resource DLL Wizard.

library ZabbixTray;

{ITE} {DFMFileType} {UMain.dfm}
{ITE} {RCFileType} {Win32\Debug\ZabbixTray_DRC.rc}

{$R 'UMain.dfm' 'frmTZMain:TForm'}
{$R 'Win32\Debug\ZabbixTray_DRC.res' 'Win32\Debug\ZabbixTray_DRC.rc'}

{$E RUS}

begin
end.
